export const PRIVATE_KEY="DRIyhr57m598HWj0hrh6q"
export const USER_ID="1Q61j7hXXuj7KGY9x"
export const TEMPLATE_ID="contact_form_template"
export const SERVICE_ID="contact_form_service"
export const url="https://api.emailjs.com/api/v1.0/email/send"
export const method="post"
